kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-runner
  namespace: runner
subjects:
- kind: ServiceAccount
  name: default
  namespace: runner
roleRef:
  kind: Role
  name: kube-runner
  apiGroup: rbac.authorization.k8s.io
